### ISSUE TITLE
the restart button on travis

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-rugs/rug-functions-travis#11]
![screen shot 2017-05-24 at 11 20 03 am](https://cloud.githubusercontent.com/assets/1643888/26419126/82c8b4f4-4073-11e7-91e8-2385d6127b9f.png)

looks like we'll need some interpretation of this error.  I assume that there's something upstream that is not being sent correctly to this function?

**Comment by ddgenome** [comment]
Where are you seeing this? Did it occur at 1:17 AM PDT this morning?

**Comment by ddgenome** [comment]
Moving this to atomist/travis-rugs/issues/14
